name: Checks

on:
  workflow_call:
    inputs:
      features-flag:
        required: true
        type: string

env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

permissions:
  contents: read

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --tests --no-default-features ${{ inputs.features-flag }}

  miri:
    name: Miri

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Setup Miri
        run: cargo miri setup

      - name: Run Miri
        run: cargo miri test --no-default-features ${{ inputs.features-flag }}

  clippy:
    name: Clippy

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run Clippy
        run: cargo clippy --no-default-features ${{ inputs.features-flag }}
